### PR TITLE
[#22] Copy with equal paths behavior fix

### LINKED ISSUE #22: `coffer copy` with two equal paths behavior
In #13 next behavior was proposed: throwing an error (like `cp` command), regardless of whether `-f` was used.

### PR DESCRIPTION
**Pull request by sancho20021**
### Problem
Currently copying entry / directory to itself is allowed in force mode.

This copying is very unnecessary, we can't see such behavior in
standard Unix `cp` command. The same applies to renaming
entries to it's current name.

### Solution
Check qualified paths for equality before copying.

## Related issue(s)

Fixed #22 

#### Related changes (conditional)

- Tests
  - [x] If I added new functionality, I added tests covering it.
  - [x] If I fixed a bug, I added a regression test to prevent the bug from
        silently reappearing again.

- Documentation
  - [x] I checked whether I should update the docs and did so if necessary:
    - [README](../tree/master/README.md)
    - Haddock

#### Stylistic guide (mandatory)

- [x] My commits comply with [the policy used in Serokell](https://www.notion.so/serokell/Where-and-how-to-commit-your-work-58f8973a4b3142c8abbd2e6fd5b3a08e).
- [x] My code complies with the [style guide](../tree/master/docs/code-style.md).

### CODE REVIEW

File: lib/Backend/Commands.hs [hunk 1]
```diff
@@ -319,6 +319,10 @@ buildCopyOperations
 buildCopyOperations oldBackend newBackend oldQPath@(QualifiedPath oldBackendNameMb oldPath) (QualifiedPath newBackendNameMb newPath) force = do
   entryOrDir <- getEntryOrDirThrow oldBackend CPRPathNotFound oldQPath
 
+  -- Don't need to copy directory or entry to itself
+  when ((oldBackendNameMb == newBackendNameMb) && (oldPath == newPath)) $
```
Comment (DK318) [inline lib/Backend/Commands.hs:323]: We could simplify this check like this
````haskell
when (oldQPath == newQPath) do
...
````

File: tests/golden/copy-command/copy-command.bats [hunk 2]
```diff
@@ -277,3 +277,41 @@ EOF
...
+
+@test "copy an entry to itself" {
+  coffer create /a
+
+  run coffer copy -f /a /a
+
+  assert_failure
+  assert_output "[ERROR] '/a' and '/a' are the same path."
+
+  run cleanOutput
```
Comment (DK318) [inline tests/golden/copy-command/copy-command.bats:289]: We don't need `cleanOutput` here. It just replaces all timestamps in the output

**Review by DK318 — CHANGES_REQUESTED** [review]
Please turn on trimming trailing whitespace in your editor.

File: lib/Backend/Commands.hs (hunk 1 above)
Comment (sancho20021) [reply lib/Backend/Commands.hs]: Done

File: tests/golden/copy-command/copy-command.bats (hunk 2 above)
Comment (sancho20021) [reply tests/golden/copy-command/copy-command.bats]: Ok, removed

**Comment by sancho20021** [comment]
> 

Yes, thanks! Didn't have that in my configuration

**Comment by dcastro** [comment]
There's an issue with the xrefcheck step in the pipeline, @DK318 is working on it (see #79).

Once his PR is merged, please rebase your branch on top of main, and the pipeline for your PR should start passing.

File: tests/golden/copy-command/copy-command.bats [hunk 3]
```diff
@@ -313,3 +313,26 @@ EOF
     b - [2000-01-01 01:01:01]
 EOF
 }
+
+@test "equal paths copy from one backend to the other" {
+  coffer create /a/b
+
+  run coffer copy /a second#/a
```
Comment (DK318) [inline tests/golden/copy-command/copy-command.bats:320]: Hmm. Maybe we need the test like this
````
coffer copy vault-local#/a vault-local#/a -f
````

**Review by DK318 — COMMENTED** [review]
LGTM

File: tests/golden/copy-command/copy-command.bats (hunk 3 above)
Comment (sancho20021) [reply tests/golden/copy-command/copy-command.bats:335]: Done. Btw, this test showed that I forgot to include backend names when showing paths in the error message. Now it is fixed

File: lib/CLI/Types.hs [hunk 4]
```diff
@@ -73,7 +73,7 @@ data CopyResult
   = CPRSuccess [(QualifiedPath EntryPath, QualifiedPath EntryPath)]
   | CPRPathNotFound (QualifiedPath Path)
   | CPRMissingEntryName
-  | CPRSamePath Path Path
+  | CPRSamePath (QualifiedPath Path) Path
```
Comment (DK318) [inline lib/CLI/Types.hs:76]: Why not `CPRSamePath (QualifiedPath Path) (QualifiedPath Path)`?

File: app/Main.hs [hunk 5]
```diff
@@ -190,8 +190,10 @@ main = do
       pathNotFound :: Member (Embed IO) r => QualifiedPath Path -> Sem r ()
       pathNotFound path = printError $ "Entry or directory not found at '" +| path |+ "'."
 
-      samePaths :: Member (Embed IO) r => Path -> Path -> Sem r ()
-      samePaths old new = printError $ "'" +| old |+ "' and '" +| new |+ "' are the same path."
+      samePaths :: Member (Embed IO) r => QualifiedPath Path -> Path -> Sem r ()
+      samePaths old@(QualifiedPath backend _) newPath =
+        printError $ "'" +| old |+ "' and '" +|
+          (QualifiedPath backend newPath) |+ "' are the same path."
```
Comment (DK318) [inline app/Main.hs:196]:
```suggestion
      samePaths :: Member (Embed IO) r => QualifiedPath Path -> QualifiedPath Path -> Sem r ()
      samePaths oldPath newPath =
        printError $ "'" +| oldPath |+ "' and '" +|
          newPath |+ "' are the same path."
```

File: app/Main.hs [hunk 6]
```diff
@@ -188,6 +190,11 @@ main = do
       pathNotFound :: Member (Embed IO) r => QualifiedPath Path -> Sem r ()
       pathNotFound path = printError $ "Entry or directory not found at '" +| path |+ "'."
 
+      samePaths :: Member (Embed IO) r => QualifiedPath Path -> Path -> Sem r ()
+      samePaths old@(QualifiedPath backend _) newPath =
+        printError $ "'" +| old |+ "' and '" +|
+          (QualifiedPath backend newPath) |+ "' are the same path."
```
Comment (dcastro) [inline app/Main.hs:196]: Instead of extracting the backend from `oldQPath :: QualifiedPath Path` and adding it to `newPath :: Path`, we could just save the qualified `newQPath :: QualifiedPath Path` inside `CPRSamePath`?

Or even just save one of the two paths (since they're the same anyway)?

Comment (sancho20021) [reply app/Main.hs:196]: Oh, really, I will just leave one of them. I think in the beginning I decided to pass two, because I thought they might have different string representations 🤣

File: lib/CLI/Types.hs (hunk 4 above)
Comment (sancho20021) [reply lib/CLI/Types.hs]: Removed second argument

File: app/Main.hs (hunk 5 above)
Comment (sancho20021) [reply app/Main.hs]: Removed second argument
